### ISSUE TITLE
utils::browseURL in exercise() does nothing (at least on Ubuntu)

### ISSUE THREAD

**Issue by richardjtelford** [PsyTeachR/msc-data-skills#12]
At least on Ubuntu, this line in `exercise()` does nothing.

https://github.com/PsyTeachR/msc-data-skills/blob/cf948ca23e6a23486eb619649342f8cc8ab7f591/R/exercise.R#L24

Consider using `rstudioapi::navigateToFile(filename)` which will open the file in Rstudio.

To allow for anyone not using Rstudio, it might be worth either using `usethis::edit_file` directly or copying the last few lines from that function into `exercise()` which tests if Rstudio is being used and opens the file in an appropriate way.

I can send a pull request if you want, but cannot test on windows machine

**Comment by debruine** [comment]
Ah, good idea! I started developing that after lockdown last year, so have really only been testing it on my Mac at home. 

The book and class are so focussed on using R with RStudio that I don’t think it makes much sense to build in workarounds. People who use something different generally know what works for their setup. 

Send a pull request of you can be bothered, or I’ll get to it eventually here.
