### ISSUE TITLE
tidyverse dependency

### ISSUE THREAD

**Issue by red-solaris** [PsyTeachR/msc-data-skills#14]
I got

`Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called 'tidyverse'
Calls: <Anonymous> ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted
ERROR: lazy loading failed for package 'dataskills'`

when trying to install had to install tidyverse manually as it does not seem to be registered as a dependency.
Also this contains some packages that need compiling in windows so you need Rtools40 setup
Also watch out for Microsoft R Open and its shitty CRAN repository snapshot
Was hoping R would be less of a shitshow than python with package management alas

**Comment by debruine** [comment]
Thanks. I should add a warning somewhere. I was having huge problems with students not being able to install it until I removed tidyverse as a dependency (although that’s not a long term solution https://www.tidyverse.org/blog/2018/06/tidyverse-not-for-packages/), but our teaching workflow just has them use library(tidyverse) at the top of scripts so they don’t have to figure out what functions are in what package right away.

**Comment by debruine** [comment]
I just accepted a pull request from Richard Telford that should fix this.
