### ISSUE TITLE
Simulation exercises, required simulations to achieve correct result

### ISSUE THREAD

**Issue by CGMossa** [PsyTeachR/msc-data-skills#6]
In `08_sim_exercise.Rmd` on question 4, a power-level is to be estimated through simulation. The required simulation level before getting a `correct`-flag is `10000` (or `1e4`).

**Comment by debruine** [comment]
Thanks for flagging this. I think I can't rely on students doing things in exactly the same way and order as I did, so I'll have to loosen the tolerance on checking simulated data.
