### ISSUE TITLE
Parsing error with CSV: US CDC Growth Chart Data Tables

### ISSUE THREAD

**Issue by CGMossa** [PsyTeachR/msc-data-skills#7]
The CSV used in `08_sim_exercise.Rmd` at Question 7 is [US CDC Growth Chart Data Tables](https://www.cdc.gov/growthcharts/data/zscore/zstatage.csv). 

This CSV file is confusing in a few ways. First, beginning in line 435, it looks like this:

```
1,240.5,162.4776756,166.0916092,169.6925342,173.2808172,176.8568057,180.4208299,183.9732035,187.5142253,191.0441799
,,,,,,,,,,
,,,,,,,,,,
,,,,,,,,,,
Sex,Agemos,-2,-1.5,-1,-0.5,0,0.5,1,1.5,2
2,24,78.02185636,79.76434516,81.50408026,83.24112888,84.97555512,86.70742016,88.43678251,90.16369812,91.88822059
2,24.5,78.40361515,80.15493488,81.90429469,83.65174068,85.3973169,87.14106545,88.8830266,90.62323896,92.36173951
```
 Also, `Agemos` has range from 24 to 240.5. What is the `Agemos`?

**Comment by CGMossa** [comment]
More information: Explanation is [here](https://www.cdc.gov/growthcharts/zscore.htm). 

> The values corresponding to specific z-scores (-2, -1.5,-1,-0.5,0, 0.5,1,1.5,2)  [...]

And 

> These files contain the z-scores values for the z-scores of –2, -1.5, -1, -0.5, 0, 0.5, 1, 1.5, and 2 by sex (1=male; 2=female) and half month of age. For example, 1.5 months represents 1.25-1.75 months. The only exception is birth, which represents the point at birth.

**Comment by debruine** [comment]
That's a ridiculously complicated question for testing that skill! I'm going to totally re-write it.
