### ISSUE TITLE
useful to package up?

### ISSUE THREAD

**Issue by richarddmorey** [PsyTeachR/msc-data-skills#9]
When compiling this, I noted that it would be useful to put into an R package so that package dependencies could be installed automatically and the entire book could be installed locally with devtools. Would this be useful for me to send over as a pull request?

**Comment by debruine** [comment]
Hi Richard,

Great idea! This would be useful if you have the time and inclination (I’m on holiday until Wednesday), but I can definitely figure it out myself if it’s a hassle. I’ll get all the psyTeachR team to do the same for their dependencies.

The bookdown version of this course still needs a fair amount of bug-checking (converting from the web version wasn’t entirely straightforward). This is on my to-do list before I start teaching this course again in September, so I’ll probably catch a lot of the little things soon, but I really appreciate your edits and any suggestions/corrections!

Cheers,
Lisa

**Comment by richarddmorey** [comment]
Candice and I are potentially going to use it for set of informal meetings for staff next year. I'll try to package it up soon. Maybe we do an exercise where all the attendees fix a typo to learn GitHub :)

**Comment by debruine** [comment]
Done! Thanks for the idea.

I wrote. tutorial about it at https://psyteachr.github.io/book-template/setup.html#converting-to-a-package
